# Generated by Django 4.2.17 on 2025-01-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indieauth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorizationcode',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='bearertoken',
            name='client',
        ),
        migrations.AddField(
            model_name='bearertoken',
            name='client_id',
            field=models.URLField(default='', max_length=2048),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
