# Generated by Django 4.2.17 on 2025-01-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indieauth', '0002_remove_authorizationcode_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizationcode',
            name='client_id',
            field=models.URLField(default='', max_length=2048),
            preserve_default=False,
        ),
    ]
