# Generated by Django 4.2.17 on 2025-01-16 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indieauth', '0003_authorizationcode_client_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.URLField(max_length=2048, unique=True)),
                ('client_name', models.TextField(null=True)),
                ('client_uri', models.URLField(max_length=2048)),
                ('logo_uri', models.URLField(max_length=2048, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RedirectUri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.URLField(max_length=2048)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redirect_uris', related_query_name='redirect_uri', to='indieauth.client')),
            ],
        ),
    ]
