# Generated by Django 4.2.17 on 2025-01-16 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indieauth', '0004_client_redirecturi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redirecturi',
            name='client',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='RedirectUri',
        ),
    ]
