# Generated by Django 4.2.17 on 2025-01-17 19:05

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('indieauth', '0005_remove_redirecturi_client_delete_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bearertoken',
            name='issued_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bearertoken',
            name='me',
            field=models.URLField(default=datetime.datetime(2025, 1, 17, 19, 5, 51, 787574, tzinfo=datetime.timezone.utc), max_length=2048),
            preserve_default=False,
        ),
    ]
